version: "3"
services:
    mariadb:
        image: 'mariadb:latest'
        restart: 'always'
        environment:
          MYSQL_USER: 'webapplication'
          MYSQL_PASSWORD: '653rag9T'
          MYSQL_DATABASE: 'videgrenierenligne'
          MYSQL_ROOT_PASSWORD: 'xyfec148'
        ports:
          - '3306:3306'
        volumes:
          - ./import.sql:/docker-entrypoint-initdb.d/import.sql
        
    phpmyadmin:
        image: 'phpmyadmin'
        restart: 'always'
        ports:
          - '8091:80'
        depends_on:
          - mariadb
        environment:
          PMA_HOST: mariadb
    
    videgrenier:
        image: 'videgrenier'
        build:
          context: .
          dockerfile: Dockerfile
        environment:
          -ALLOW_OVERRIDE: 'true'
          -user: 'root'
          -db: 'mariadb'
          -password: 'root' 
        depends_on:
          - mariadb  
        ports:
          - '8090:80'
     