version: "3"
services:
    mariadb_production:
        container_name: mariadb_production
        image: 'mariadb:latest'
        restart: 'always'
        environment:
          MYSQL_USER: 'webapplication'
          MYSQL_PASSWORD: '653rag9T'
          MYSQL_DATABASE: 'videgrenierenligne'
          MYSQL_ROOT_PASSWORD: 'root'


        ports:
          - '9000:3306'
        volumes:
          - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
        
    phpmyadmin_production:
        image: 'phpmyadmin'
        restart: 'always'
        ports:
          - '9001:80'
        depends_on:
          - mariadb_production
        environment:
          PMA_HOST: mariadb_production
    
    videgrenier_production:
        image: 'videgrenier'
        ports:
          - '9002:80'
          - '9003:22'
        build:
          context: .
          dockerfile: Dockerfile
        environment:
          ALLOW_OVERRIDE: 'true'
          user: 'root'
          db: 'mariadb'
          password: 'root' 
          MYSQL_HOST: mariadb_production

        depends_on:
          - mariadb_production

       
        
     